

#define MAX_TASKS 9
#define MAX_NOT_SUSPENDED MAX_TASKS
#define MAX_NUMBER_PRIORITY 255
#define NUMBER_TASKS_PER_PRIORITY MAX_TASKS // BCC2 e ECC2
#define MAX_ACTIVATION_TASKS MAX_TASKS
#define NUMBER_ALARMS 255
#define NUMBER_NESTED_RESOURCE 255
#define LOWEST_PRIORITY_USED_BY_OS 1
