#ifndef PIC18F25K80_INTERRUPTS_H
#define PIC18F25K80_INTERRUPTS_H

#include <xc.h>

#define PLATFORM_ENABLE_GLOBAL_INTERRUPTS ei
#define PLATFORM_DISABLE_GLOBAL_INTERRUPTS di

#define PLATFORM_IS_ON_INTERRUPT() (INTCONbits.GIE == 0)

#endif//PIC18F25K80_INTERRUPTS_H