#ifndef PIC18F25K80_INTERRUPTS_H
#define PIC18F25K80_INTERRUPTS_H

#include <xc.h>

#define PLATFORM_ENABLE_GLOBAL_INTERRUPTS ei
#define PLATFORM_DISABLE_GLOBAL_INTERRUPTS di

#endif//PIC18F25K80_INTERRUPTS_H